### ISSUE TITLE
Full art Trainer cards

### ISSUE THREAD

**Issue by DefinitelyNotKiara** [lvandernoll/pkm-card-maker#42]
Hey,
I wounder if it would be possible to add full art trainer cards to the application?

I have been using it for a while and for me its definitely missing.

I would be very happy if it would get added

Greetings
Kiara

**Comment by lvandernoll** [comment]
Hey there, sorry for responding so late. I didn't know this repo got any traction 😛 

Sadly I'm no artist or graphic designer. I used templates from [aschefield](https://www.deviantart.com/aschefield101) (you can see his watermark on the bottom of the templates), and when asked he noted he's been way too busy with work for the past 2 years.

If you find anything or can make it yourself, make sure it's in the [right format](https://github.com/lvandernoll/pkm-card-maker/blob/master/public/assets/Trainer/SS_Trainer_Supporter.png) (size, resolution, etc.) and you could either make a PR or post it here and I'll do it.

Kind regards,
Leon

**Comment by UmbreonJPN** [comment]
Hello I make one. 
![SWSH Fullart Trainer](https://user-images.githubusercontent.com/100189714/155153209-73df0ce9-de52-42f0-92ed-0767afce7e0b.png)

**Comment by lvandernoll** [comment]
@UmbreonJPN thanks, looks good! Any chance you could translate it to English, like this?
![image](https://user-images.githubusercontent.com/36536517/155153634-1d3b816d-85df-44fe-b628-9ed2fa65c551.png)

**Comment by UmbreonJPN** [comment]
Yes Wait

**Comment by UmbreonJPN** [comment]
So, 
![155153209-73df0ce9-de52-42f0-92ed-0767afce7e0b](https://user-images.githubusercontent.com/100189714/155162703-68ae905a-3c18-4651-b802-2ab6be0cf5b8.png)
here is the Card and Please add it.
