### ISSUE TITLE
Is it possible to add Star card ?

### ISSUE THREAD

**Issue by Senju0** [lvandernoll/pkm-card-maker#59]
I have the template
[Star by Runecript.zip](https://github.com/lvandernoll/pkm-card-maker/files/8180088/Star.by.Runecript.zip)
Example :
![PKMN_star_C](https://user-images.githubusercontent.com/100858901/156626168-4013ecde-4a9d-4bad-a569-3e4a90761b26.png)

**Comment by lvandernoll** [comment]
I will look into it soon. Thanks for the template!

**Comment by lvandernoll** [comment]
Added this in a new update. You can access it under the 'Rarity' dropdown when you have selected a Basic pokémon
![image](https://user-images.githubusercontent.com/36536517/159166820-e05eec22-8d32-4aed-b3ea-5049d8817487.png)
